AlaskaAirlines/WC-Generator

bin/generate.js

This PR adds a function that checks key dependency version numbers of web components generated with wc-generator. This ensures these key dependencies are the latest versions.

fix(generator): add dynamic versioning

---

bin/generate.js
package-lock.json
package.json
template/.github/ISSUE_TEMPLATE/user-story.md
template/README.md
template/docs/index.html
template/package.temp
template/webpack.config.js

The scope of this update is to address the following issues: 
1. Update user-story issue template 

Release #10

---

template/karma.conf.js

Upon new components, running `npm run test` generates the following error due to an API change from the 'merge' package:
Removes default export reliance from the karma.config template. …

Karma Merge reference fix

---

template/package.temp

**Fixes:** # (issue, if applicable)
add / into name: of package.json
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of …

fix: add / into name: of package.json

---

template/README.md

**Fixes:** # (issue, if applicable)
Missing / in the ReadMe between the template that generates `@alaskaairux/component-name`
Added the / in the three locations it was missing. Found it while updating the icon component that was generated from this release.
_Pull Requests will be evaluated by …

fix: add missing / between [npm] and [namespace]-[name]

---

template/.gitignore.temp
template/README.md
template/demo/index.html
template/package.json
template/scripts/prepForBuild.js

This PR adds support for building a deployable version of the component demo. 

feat: add support for deployable demo build

---

docs/test-runner.md

This PR adds WSL setup notes to the testing docs.

docs: add WSL troubleshooting instructions

---

docs/auroLabs.md
docs/auroLabsMajors.md
docs/auroLabsMinors.md
docs/customElementCss.md

**Fixes:** https://github.com/AlaskaAirlines/WC-Generator/issues/74
The scope of this update is to add more depth and understanding around the process of AuroLabs.
Demo of new content can be seen
* https://auro-labs.surge.sh/aurolabs
* https://auro-labs.surge.sh/webcorestylesheets/custom-element-css
This PR has multiple assigned reviews. This new content is about a new process to be rolled out across the org and I am very interested in your perspectives as to the process laid out and the content within. 
Please feel free to reach out to me directly with feedback or add comments to this PR. 
Please delete options that …

Generator: Add full auroLabs docs

---

docs/customElementCss.md

**To help address:** https://github.com/AlaskaAirlines/auro-alerts/issues/14
This update is a content update to address an issue of documentation regarding the use of attribute selectors for UI.

Update CSS attribute use case

---

docs/devSetup.md

This adds setup instructions for WSL.
Reference: https://github.com/AlaskaAirlines/WC-Generator/issues/89

docs: add WSL setup instructions

---

docs/browserSupport.md
docs/comliance.md
docs/slots.md
docs/tests.md

**Fixes:** https://github.com/AlaskaAirlines/WC-Generator/issues/90
This PR adds content pages that were relocated from the original Auro repo. 

Generator: add relocated content 

---

README.md
bin/generate.js
docs/auroLabsMinors.md

**Fixes:** #99 
The scope of this PR updates the Generator's lead-in questions to better inform users of Auro's options and resources. 

Update generator lead questions #99

---

bin/generate.js
util/help-outputs.js

**Resolves:** #127 
The scope of this PR addresses an issue where users were unaware of what version of the generator they have installed. 

Generator: Add support for showing installed version with --help

---

docs/defineApi.md

**Resolves:** #105 
The scope of this update is to add documentation in support of more developers contributing APIs to new custom elements. 
As a follow-up, a reference to this document needs to be made from the Doc site.

Generator: Add API development guide docs

---

docs/devSetupLinux.md
docs/devSetupOsx.md
docs/devSetupWindows.md

**Resolves:** #126 
This PR updates the content structure of the preferred dev setup instructions. 

Generator: update platform dev setup docs

---

.github/CONTRIBUTING.md
README.md

**Resolves:** #124
This update includes documentation that revises the contributing guidelines for naming conventions. 

Generator: update contrib docs about branch and pr conventions

---

.husky/_/husky.sh
.husky/commit-msg
.husky/pre-commit
bin/generate.js
package-lock.json
package.json
template/.husky/_/husky.sh
template/.husky/commit-msg
template/.husky/pre-commit
template/package.json

**Fixes:** #84
This change updates Husky to v6.0.0. Additionally, the method for calling the pre-commit and commit message enforcement was changed in v6. Additional changes were made to WC Generator in order to call the same pre-commit and commit message processes that were previously in place.
-- Auro Design …

Generator: update husky version and related workflow

---

package.json
template/.github/ISSUE_TEMPLATE/dev-story.md
template/.github/ISSUE_TEMPLATE/publish_component.md

**Fixes:** #134
Adds a new ticket template for tracking compliance necessary to publish an AuroLabs component to Auro Design System

docs(template): add publish ticket type

---

util/auroMigrate.md
util/auroMigrate.sh
util/help-outputs.js

**Fixes:** #145 
This update addresses the issue where Husky was not being initialized with a migration of an older repo to a new Generator install. Another minor update was added to support the passing in of an npm namespace, specifically for the use of migrating an @aurolabs project. Last, a miss in the `--help` was addressed to update the package namespace.  …

fix(husky migration): update scripts to address husky init

---

template/.gitignore.temp

**Fixes:** #142 
Addresses an issue where the demo files were not being added to version control. 

Add ignored files for demo

---

bin/generate.js
commitlint.config.js
labsTemplate/.github/settings.yml
labsTemplate/README.md
package.json
template/commitlint.config.js
template/package.json
template/src/[namespace]-[name].js

**Fixes:** #149 
This PR encompasses a few updates. Issue #149 is addressed. As well as a commit for the purpose of adding a new feature for alternate templates if the repo is an auroLabs project. Lastly, there is a commit for a minor update regarding additional comments in the src CE template. 
-- Auro Design …

Generator: labs, commitlint and template updates 

---

template/.husky/pre-commit.temp
template/README.md
template/README__labs.md
template/package.json

**Fixes:** #147 
This PR:
1. removes bundled asset bundling from pre-commit; assets are generated in the cloud 
2. removes local watch of ./docs/api.md and will commit back the file from remote build with version update

Generator: cloud build assets 

---

template/package.json

**Fixes:** #153 
This PR follows up an update to the [Auro esLint dependency](https://github.com/AlaskaAirlines/eslint-config-auro/commit/1ecf9cc6c47ef5ca8178cd63c50a38c857de7ff9). 
This is not a bug, but it is a minor update. 

Remove local dependency for eslint-plugin-lit

---

template/package.json
template/src/es5.js

**Fixes:** #157
This change makes eslint validate all JS files in the src directory and any nested folder. Additionally, the es5.js file in the template src directory was updated to be compliant with the eslint rules.

feat(eslint): broaden eslint coverage

---

template/scripts/prepForBuild.js
util/auroMigrate.md
util/auroMigrate.sh

**Fixes:** #160, #161
Minor updates to file structure and migration. 

generator: address bugs with migrations

---

bin/generate.js
template/.github/settings.yml
template/.github/settings__labs.yml
template/README.md
template/README__labs.md

**Fixes:** #165 
This PR adds the generator version to the repo's tags. This PR also addresses a miss with the README files in applying the correct npm namespace to the bundled URLs. 

generator: add version to repo tag

---

util/auroMigrate.sh

**Fixes:** #167
This change address two minor typos in the auroMigrate.sh script.

fix(typos): correct minor typos

---

.github/settings.yml
bin/generate.js
template/.github/settings.yml
template/.github/settings__labs.yml
template/demo/demo.md
util/version-outputs.js

This PR and the previous commit address an issue of reported cases when the user tried to install an updated version of the generator, there was an incorrect strict restriction as to the baseline version of node. 

fix(test): address issue with baseline and test versions

---

template/src/[namespace]-[name].js

**Fixes:** #176 
This PR addresses a grammar issue that conflicts with JSDoc lint expectations. 

wc-generator: update comment to meet lint spec

---

bin/generate.js
template/demo/index.html

**Fixes:** #178 #175 
This PR addresses two issues. 
* #178 to pull demo CSS from CDN location
* #175 ask the user to confirm the latest installed version

generator: update demo css reference; confirm user install version

---

template/package.json

**Fixes:** #193
Change moves the `test` task before the bundlers execute in the build script.

refactor(scripts): runs tests before bundler

---

template/.github/settings.yml

**Fixes:** #190
Settings.yml updated so that branches are automatically deleted when merged.

ci(git): deletes branches on merge

---

template/README.md

**Fixes:** #197
Minor fix to correct link in readme

docs(readme): corrects url in document

---

template/README.md

**Fixes:** #195
This is a minor change to fix a typo error in the readme

docs(readme): corrects typo in demo build instruction

---

package-lock.json
package.json

This PR updates potential security vulnerabilities. 

Chore: dependency update security vulnerabilities

---

template/.github/ISSUE_TEMPLATE/publish_component.md

**Fixes:** #208
This change updates the github publish ticket with additional tasks to cover easily overlooked information as well as final publishing steps necessary after the component has been reviewed.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may …

docs(tickets): update publish ticket content

---

template/.github/ISSUE_TEMPLATE/release_candidate.md

docs(template): add release candidate issue template

---

template/package.json

**Fixes:** #215
Updates the packaage.json template to be fixed at `v2.5.1`

fix(lit): fix generator to use v2.5.1 of LitElement #215

---

.github/workflows/testPublish.yml
template/.github/workflows/testPublish.yml
util/verifyNodeVersion.js

**Fixes:** #217 
Update node verification and Github action workflows to reference correct versions of Node to ensure end-user DX. 
-- …

Address correct versions of node for verification

---

.github/CODEOWNERS
template/.github/CODEOWNERS

**Fixes:** #214 
The scope of this update reflects the changes to the team settings. This update allows for others to be added to the team that will not be pulled into pull request reviews. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to …

Update codeowners file to reflect team org updates

---

template/scripts/postCss.js

ci(postcss): remove code not compatabile with node 15

---

template/.github/settings.yml
template/.github/settings__labs.yml

feat(git): use custom namespace in settings.yml

---

template/package.json

**Fixes:** #243 
The scope of this patch is to address a build issue where bundled assets may not be building correctly due to nodes inability to find the right version of lit-HTML. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values …

Update template package to use lit-html 1.0

---

template/.github/ISSUE_TEMPLATE/release_candidate.md
template/.stylelintrc

**Fixes:** #228 #246 
The PR contains a commit that adds instructional content to the RC issue template for reference when starting a new RC project. 
This limit restricts the type of UI development required for many custom elements and due to the encapsulation of a CE, the concern about these types of selectors is not warranted. 
**By submitting this Pull Request, I confirm that my contribution is made under the …

Update issue template / selector max

---

template/demo/index.html

**Fixes:** #250 
This update will fix a build bug for local component demos.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the …

Update marked API call

---

.github/settings.yml
template/.github/settings.yml
template/.github/settings__labs.yml

**Fixes:** #184 
This PR aims to update the labels used for any new or updated repo with Auro. 
See 'demo' at https://github.com/AlaskaAirlines/test-repo/labels
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any …

Update pre-defined labels for new repo

---

template/.stylelintrc

**Fixes:** #290
This change adds local lint rules for ID and class selector syntax

fix(styles): improve selector lint rules

---

componentDocs/README.md

**Fixes:** #298
Corrects two file extensions of remote imports in the README.md template

docs(template): fix file extension in readme template

---

bin/generate.js
template/scripts/generateDocs.js

**Fixes:** #300
This change improves the generateDocs.js script achieving two goals:
1. Make the doc generate dynamically replace [npm], [namespace] and [name] variables in md docs (extensible)
1. General code cleanup since this script was starting to get fairly complex including wrapping code sections into semantic functions
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. …

feat(docs): generate docs handles dynamic npm, namespace and name

---

template/docs/partials/apiExamples.md
template/docs/partials/demo.md
template/scripts/generateDocs.js

**Fixes:** #303 
Splits demo examples into two pages:
- demo.md
- apiExamples.md (to be used in docsite in place of api.md)
api.md file remains as it was previously.
**Thank …

feat(docs): split demo examples between demo.md and new apiExamples.md

---

componentDocs/README.md
template/docs/partials/demo.md
template/docs/partials/readmeAddlInfo.md

**Fixes:** #305 
This PR includes three doc changes:
1. Move component basic example to end of the `demo.md` template
1. Add a comment section to the top of the `readme.md` template explaining the document is a compiled document.
1. Adds an import section to the `readme.md` template file that can be used (or left empty) for any custom content the component developer feels should be included/added to the readme but does not make sense to include in the description or the use case sections of the document. There is no requirement to include any custom information, and no component currently includes any information …

Jbaker/update doc templates/#305

---

util/auroMigrate.md
util/auroMigrate.sh

**Fixes:** #302 
This change makes the migrate script also copy the ./apiExamples directory from the legacy repo.
-- Auro Design System …

refactor(migrate): add apiExamples to migrate script

---

template/.github/workflows/testPublish.yml

**Fixes:** #288 
the node version was hard coded to 14 and this change makes it dynamically set on the same manner its set elsewhere in the settings.
**Thank you for your …

fix(git): correct node version in github release workflow

---

template/.github/ISSUE_TEMPLATE/blueprint.md

**Fixes:** #313 
Add new Component Blueprint issue template

feat(git): add new component blueprint issue template

---

docs/bestPractices.md

modified:   docs/bestPractices.md
**Resolved:** #159 
The scope of this PR is to add documentation regarding custom element definitions and registration order. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and …

Add docs regarding dependency defs

---

package-lock.json
package.json

modified:   package.json
This is a PR to address some dependency updates. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the …

chore(deps): update semantic release

---

.github/SECURITY.md
.github/workflows/codeql.yml

**Resolves:** #318
This PR adds a commit to create a new default Github security policy to alert users of how to properly report a potential security issue with any Auro component. 
This PR also adds a workflow config file that will perform code quality checks against the repo with merges and pull requests.
**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Add security policy

---

componentDocs/partials/usage/componentInstall.md

**Resolves:** #321 
This commit will add an automated capability to the README docs to present a security vulnerabilities check.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a …

Add npm package vulnerabilities badge

---

.github/SECURITY.md
.github/workflows/codeql.yml
componentDocs/partials/usage/componentInstall.md

This PR is the v3.17 release of pre-approved PR commits. 

v3.17-rc release

---

template/rollup.config.js

**Resolves:** #257
This feature adds a check in the rollup config that will compare the auro-* files in the src dir against the rollup config input. If these are out of sync a warning will be written to the console log.
_Pull Requests will be evaluated by their quality of update and whether it is …

Compare config to src files

---

template/.github/workflows/testPublish.yml

modified:   template/.github/workflows/testPublish.yml
**Resolves:** #366 
Updates the dependency versions for the Github Actions workflow file.  …

perf(workflow): update dependency versions #366

---

template/demo/index.html

modified:   template/demo/index.html
**Fixes:** #389 
This update replaces a missing reference to the src js file for the demos. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any …

Replace missing js reference #389

---

componentDocs/partials/usage/bundleUse.md

**Fixes:** #395
Reference the correct URL for the design token style sheet via CDN

docs(bundles): use correct url for design token CDN #395

---

componentDocs/partials/usage/bundleUse.md

**Fixes:** #401
Fixes the URL for the component bundle in bundleUse.md

docs(bundles): correct url for component bundle #401

---

template/demo/api.html

**Resolves:** #404 
This commit adds a new api.html file template to be used with the generation of the apiExamples.md file.
new file:   template/demo/api.html
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and …

Add api html file

---

template/.github/workflows/autoAssign.yml

**Resolved:** #399 
Adds support for auto-applying assignees to new issues as they are created. 
new file:   template/.github/workflows/autoAssign.yml
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this …

perf: add auto assign workflow action #399

---

template/demo/api.html
template/demo/index.html

feat: update demos with neccessary attribute for surge #415

---

componentDocs/README.md

**Fixes:** #417 
Remove the Demo Deployment section of the readme.md file as it is no longer valid.

docs(readme): remove demo deployment section #417

---

template/src/style.scss

**Fixes:** #424
Template sass file needed updating to new import paths for latest WCSS and Design Token Releases.
-- Auro Design System …

fix(build): correct paths for latest WCSS and design token versions #424

---

template/docs/partials/apiExamples.md

**Fixes:** #454
Remove invalid HTML from API doc template.

fix(docs): remove invalid HTML for API doc template #454

---

componentDocs/README.md
componentDocs/README_v4.md
componentDocs/partials/usage/cssFallbacks.md

**Resolves:** #435
Remove documentation about lack of support for CSS Fallbacks on older browsers.

docs(css): remove documentation about CSS Fallbacks #435

---

package-lock.json
package.json

Moves Auro Library into `dependencies` from `devDependencies` to avoid installation issues, as originally reported in [#573](https://github.com/AlaskaAirlines/WC-Generator/issues/573).
**Resolves:** #575 
- Moved to `dependencies` within `package.json`
- Regenerated `package.lock`
- Verified `build` and `test` ran successfully
**Thank you for your …

fix: moves auro library to dependencies in package.json #575
